["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo-path = [
    "./lib/open_zeppelin/src/",
]

["protostar.contracts"]
Operator = [
    "src/Operator.cairo",
]
TimeToken = [
    "src/TimeToken.cairo"
]
MyContract = [
    "src/MyContract.cairo"
]

["profile.devnet.protostar.shared_command_configs"]
gateway_url = "http://127.0.0.1:5050/"
chain_id = 1536727068981429685321
