["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.shared_command_configs"]
cairo-path = [
    "./lib/cairo_contracts/src",
    "./lib/helper"
]

["protostar.contracts"]
main = [
    "src/main.cairo",
]
erc20x = [
    "src/token/erc20x.cairo"
]

["profile.devnet.protostar.deploy"]
gateway_url = "http://127.0.0.1:5050/"
chain_id = 1536727068981429685321
