[project]
protostar-version = "0.7.0"
lib-path = "lib"
cairo-path = ["./lib/cairo_contracts/src", "./lib/helper"]

[contracts]
BudiOperator = ["src/budi_operator.cairo"]
BudiCredit = ["src/budi_credit.cairo"]

[profile.devnet.deploy]
gateway_url = "http://127.0.0.1:5050/"
chain_id = 1536727068981429685321