#! /usr/bin/env bash

main_contract_owner=0x1f801022ab0deb6b98c94c9daaec770da7d17f962ad8cde34dddab58c0c18ce
token_contract_address=0
account_to_be_funded=0x7c4d7ff0b3eca8a7a95a69b46938ea06f2d5b321e132c71c39405279dad4d26

function deploy_token {
  local name=$(cairo-cast TIMETOKEN)
  local symbol=$(cairo-cast TIME)
  token_contract_address=$(protostar -p devnet deploy ./build/erc20x.json --inputs $name $symbol 18 100000000 $main_contract_owner 2>&1 | grep "Contract address")
}

function deploy_main {
  protostar -p devnet deploy ./build/main.json --inputs $main_contract_owner ${token_contract_address/Contract address: /}
}

function fund_account {
  ./scripts/invoke erc20x --address ${token_contract_address/Contract address: /} --function transfer --inputs $account_to_be_funded 1000 --account main_contract_owner
}

deploy_token && deploy_main && fund_account
